version: '3.8'

services:
  # Node app
  app:
    image: kamarafidele/expense_tracker:latest
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
    networks:
      - expense-network

  # nginx reverse-proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge
