version: '3.8'

services:
  # Node app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # EXPOSE it to the internal Docker network
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    networks:
      - expense-network

  # nginx reverse-proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - expense-network

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    networks:
      - expense-network

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    networks:
      - expense-network

volumes:
  postgres-data:
  redis-data:

networks:
  expense-network:
    driver: bridge
